name: product_quote_builder
description: Responsive Product Quote Builder app.
version: 1.0.2+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  uuid: ^3.0.7
  google_fonts: ^5.0.0
  font_awesome_flutter: 10.4.0
  printing: ^5.11.0
  pdf: ^3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
